
let adminUser=null,days=[],students=[],allTargets=[];
function tab(n,el){["dashboard","students","targets","tests","pdfs","messages","reports","settings"].forEach(x=>document.getElementById(x+"Tab").classList.toggle("hidden",x!==n));document.querySelectorAll(".sidebar a").forEach(a=>a.classList.remove("active"));if(el)el.classList.add("active")}
async function guard(){adminUser=await requireAuth();if(!adminUser)return false;const p=await getProfile(adminUser.id);if(p?.role!=="admin"){alert("Admin access required");location.href="student.html";return false}return true}
async function init(){if(!(await guard()))return;todayDate.textContent=new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"});await loadDays();await loadStudents();await Promise.all([loadDashboard(),loadTests(),loadMaterials(),loadReports()])}
async function loadDays(){const r=await sb.from("schedule_days").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).order("day_number");days=r.data||[];const opts=days.map(d=>`<option value="${d.id}">Day ${d.day_number} — ${fmtDate(d.day_date)}</option>`).join("");targetDay.innerHTML=opts;pdfDay.innerHTML=opts;testDay.innerHTML='<option value="">No linked day</option>'+opts;await loadVerificationTargets();await loadTargetStatus()}
async function loadStudents(){const r=await sb.from("profiles").select("*").eq("role","student").order("created_at",{ascending:false});students=r.data||[];renderStudents(students)}
function renderStudents(list){studentsBody.innerHTML=list.map(s=>`<tr><td><b>${esc(s.full_name||"")}</b></td><td>${esc(s.phone||"")}</td><td>${s.total_completed_days||0}/90</td><td>${s.average_test_percentage||0}%</td><td>${s.current_streak||0} Days</td><td><span class="badge badge-blue">Active</span></td></tr>`).join("")}
function filterStudents(){const q=studentSearch.value.toLowerCase();renderStudents(students.filter(s=>(s.full_name||"").toLowerCase().includes(q)||(s.phone||"").includes(q)))}
async function loadDashboard(){
 const today=new Date().toISOString().slice(0,10);const d=await sb.from("schedule_days").select("id").eq("day_date",today).maybeSingle();let p=[];if(d.data){const r=await sb.from("daily_progress").select("*").eq("schedule_day_id",d.data.id);p=r.data||[]}
 const c=p.filter(x=>x.status==="completed").length,partial=p.filter(x=>x.status==="partial").length,not=p.filter(x=>x.status==="not_started").length,pending=p.filter(x=>x.status==="test_pending").length;
 kpis.innerHTML=`<div class="kpi-card kpi-blue span-3"><div class="muted">Total Students</div><div class="kpi">${students.length}</div></div><div class="kpi-card kpi-green span-3"><div class="muted">Target Completed</div><div class="kpi">${c}</div></div><div class="kpi-card kpi-orange span-3"><div class="muted">Partial Completed</div><div class="kpi">${partial}</div></div><div class="kpi-card kpi-red span-3"><div class="muted">Not Started</div><div class="kpi">${not}</div></div>`;
 overviewLegend.innerHTML=`<p>🟢 Completed: ${c}</p><p>🟠 Partial: ${partial}</p><p>🔴 Not Started: ${not}</p><p>🔵 Test Pending: ${pending}</p>`;
 quickSummary.innerHTML=`<div class="item"><b>Today Active Students</b><div class="kpi">${p.length}</div></div><div class="item"><b>Average Test</b><div class="kpi">${students.length?Math.round(students.reduce((a,s)=>a+(s.average_test_percentage||0),0)/students.length):0}%</div></div>`;
}
async function loadTargetStatus(){
 const dayId=targetDay.value||days[0]?.id;if(!dayId)return;const r=await sb.from("daily_progress").select("*,profiles(full_name)").eq("schedule_day_id",dayId);const rows=r.data||[];
 const c=rows.filter(x=>x.status==="completed").length,partial=rows.filter(x=>x.status==="partial").length,not=rows.filter(x=>x.status==="not_started").length,pending=rows.filter(x=>x.status==="test_pending").length;
 targetStatusCards.innerHTML=`<div class="kpi-card kpi-green span-3"><div class="muted">Completed</div><div class="kpi">${c}</div></div><div class="kpi-card kpi-orange span-3"><div class="muted">Partial</div><div class="kpi">${partial}</div></div><div class="kpi-card kpi-red span-3"><div class="muted">Not Started</div><div class="kpi">${not}</div></div><div class="kpi-card kpi-blue span-3"><div class="muted">Test Pending</div><div class="kpi">${pending}</div></div>`;
 targetStatusBody.innerHTML=rows.map(x=>`<tr><td>${esc(x.profiles?.full_name||"")}</td><td>${x.completed_targets}/${x.total_targets}</td><td>${x.test_score_percent??"-"}%</td><td>${esc(x.status)}</td><td>${x.status==="completed"?"Excellent 🌹":x.status==="partial"?"Target पूरा करें ⚠️":x.status==="test_pending"?"Test Complete करें 📝":"Work Complete नहीं हुआ ❌"}</td></tr>`).join("");
}
async function loadVerificationTargets(){const dayId=pdfDay.value||days[0]?.id;if(!dayId)return;const r=await sb.from("daily_targets").select("*").eq("schedule_day_id",dayId).order("target_order");allTargets=r.data||[];verifyTarget.innerHTML=allTargets.map(t=>`<option value="${t.id}">${esc(t.subject)} — ${esc(t.topic)}</option>`).join("")}
pdfDay?.addEventListener?.("change",loadVerificationTargets);
async function createTargetVerification(){
 const target=allTargets.find(t=>t.id===verifyTarget.value);if(!target){toast("Target चुनें","error");return}
 const q=await sb.from("verification_questions").insert({schedule_day_id:target.schedule_day_id,target_id:target.id,verification_kind:verifyKind.value,question_text:verifyQuestion.value.trim(),answer_type:"text",is_active:true}).select().single();if(q.error){toast(q.error.message,"error");return}
 const k=await sb.from("verification_answer_keys").insert({verification_question_id:q.data.id,correct_answer:verifyAnswer.value.trim()});if(k.error){toast(k.error.message,"error");return}
 toast("Verification save हो गया","success");verifyQuestion.value="";verifyAnswer.value="";
}
async function loadTests(){const r=await sb.from("tests").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).order("created_at",{ascending:false});adminTests.innerHTML=(r.data||[]).map(t=>`<div class="item"><b>${esc(t.title)}</b><div class="muted">${t.total_questions} Questions • ${t.status}</div></div>`).join("")}
async function createTest(){
 let qs;try{qs=JSON.parse(questionsJson.value)}catch{toast("Invalid JSON","error");return}
 const allowed=new Set(["normal_mcq","multi_statement","statement_conclusion","assertion_reason","matching","chronology","fill_blank","correct_code","odd_one_out","multiple_statement_correctness"]);
 for(const q of qs){if(!allowed.has(q.question_type)){toast("Invalid question type","error");return}if(!Array.isArray(q.options)||q.options.length!==4){toast("हर प्रश्न में 4 options जरूरी","error");return}}
 const tr=await sb.from("tests").insert({batch_id:APP_CONFIG.BATCH_ID,schedule_day_id:testDay.value||null,title:testName.value.trim(),test_type:testType.value,total_questions:qs.length,total_marks:qs.reduce((a,q)=>a+(q.marks||1),0),time_limit_minutes:+testTime.value||null,status:"published",created_by:adminUser.id}).select().single();if(tr.error){toast(tr.error.message,"error");return}
 for(let i=0;i<qs.length;i++){const q=qs[i];const rr=await sb.from("test_questions").insert({test_id:tr.data.id,question_order:i+1,marks:q.marks||1,difficulty:q.difficulty||"normal",question_type:q.question_type,question_text:q.question_text,instructions:q.instructions||null,options:q.options,statements:q.statements||null,assertion_text:q.assertion_text||null,reason_text:q.reason_text||null,list_a:q.list_a||null,list_b:q.list_b||null,sequence_items:q.sequence_items||null,subject:q.subject||null,topic:q.topic||null}).select().single();if(rr.error){toast(rr.error.message,"error");return}await sb.from("test_question_keys").insert({question_id:rr.data.id,correct_answer:q.correct_answer,explanation:q.explanation||null})}
 toast("Test publish हो गया","success");questionsJson.value="";loadTests();
}
async function uploadPdf(){const f=pdfFile.files[0];if(!f){toast("PDF चुनें","error");return}const path=`${pdfDay.value}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await sb.storage.from("study-pdfs").upload(path,f,{contentType:"application/pdf"});if(up.error){toast(up.error.message,"error");return}const ins=await sb.from("study_materials").insert({schedule_day_id:pdfDay.value,title:pdfTitle.value.trim()||f.name,material_type:"pdf",storage_path:path,file_size_bytes:f.size,mime_type:"application/pdf",status:"published",uploaded_by:adminUser.id,published_at:new Date().toISOString()});if(ins.error){toast(ins.error.message,"error");return}toast("PDF upload हो गई","success");loadMaterials()}
async function loadMaterials(){const r=await sb.from("study_materials").select("*,schedule_days(day_number)").order("created_at",{ascending:false});materialsList.innerHTML=(r.data||[]).map(m=>`<div class="item"><b>${esc(m.title)}</b><div class="muted">Day ${m.schedule_days?.day_number||"-"}</div></div>`).join("")}
async function loadReports(){const top=[...students].sort((a,b)=>(b.total_completed_days||0)-(a.total_completed_days||0)||(b.average_test_percentage||0)-(a.average_test_percentage||0)).slice(0,5);reportCards.innerHTML=`<div class="kpi-card kpi-green span-4"><div class="muted">Targets Completed</div><div class="kpi">${students.reduce((a,s)=>a+(s.total_completed_days||0),0)}</div></div><div class="kpi-card kpi-blue span-4"><div class="muted">Students</div><div class="kpi">${students.length}</div></div><div class="kpi-card kpi-purple span-4"><div class="muted">Average Score</div><div class="kpi">${students.length?Math.round(students.reduce((a,s)=>a+(s.average_test_percentage||0),0)/students.length):0}%</div></div>`;topStudents.innerHTML=top.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.full_name||"")}</td><td>${s.total_completed_days||0}/90</td><td>${s.average_test_percentage||0}%</td></tr>`).join("")}
init();
