let adminUser=null,days=[],students=[],allTargets=[];
function tab(n,el){["dashboard","students","targets","tests","oneliners","pdfs","messages","reports"].forEach(x=>document.getElementById(x+"Tab").classList.toggle("hidden",x!==n));document.querySelectorAll(".sidebar a").forEach(a=>a.classList.remove("active"));if(el)el.classList.add("active")}
async function guard(){adminUser=await requireAuth();if(!adminUser)return false;const p=await getProfile(adminUser.id);if(p?.role!=="admin"){alert("Admin access required");location.href="student.html";return false}return true}
async function init(){if(!(await guard()))return;todayDate.textContent=new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"});await loadDays();await loadStudents();await Promise.all([loadDashboard(),loadTests(),loadOneLinersAdmin(),loadMaterials(),loadReports()])}
async function loadDays(){const r=await sb.from("schedule_days").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).order("day_number");days=r.data||[];const opts=days.map(d=>`<option value="${d.id}">Day ${d.day_number} — ${fmtDate(d.day_date)}</option>`).join("");targetDay.innerHTML=opts;pdfDay.innerHTML=opts;testDay.innerHTML='<option value="">No linked day</option>'+opts;await loadVerificationTargets();await loadTargetStatus()}
async function loadStudents(){const r=await sb.from("profiles").select("*").eq("role","student").order("created_at",{ascending:false});students=r.data||[];renderStudents(students)}
function renderStudents(list){studentsBody.innerHTML=list.map(s=>`<tr><td><b>${esc(s.full_name||"")}</b></td><td>${esc(s.phone||"")}</td><td>${s.total_completed_days||0}/125</td><td>${s.average_test_percentage||0}%</td><td>${s.current_streak||0} Days</td></tr>`).join("")}
function filterStudents(){const q=studentSearch.value.toLowerCase();renderStudents(students.filter(s=>(s.full_name||"").toLowerCase().includes(q)||(s.phone||"").includes(q)))}
async function loadDashboard(){const today=new Date().toISOString().slice(0,10);const d=await sb.from("schedule_days").select("id").eq("day_date",today).maybeSingle();let p=[];if(d.data){const r=await sb.from("daily_progress").select("*").eq("schedule_day_id",d.data.id);p=r.data||[]}const c=p.filter(x=>x.status==="completed").length,partial=p.filter(x=>x.status==="partial").length,not=p.filter(x=>x.status==="not_started").length;kpis.innerHTML=`<div class="kpi-card kpi-blue span-4"><div class="muted">Total Students</div><div class="kpi">${students.length}</div></div><div class="kpi-card kpi-green span-4"><div class="muted">Target Completed</div><div class="kpi">${c}</div></div><div class="kpi-card kpi-red span-4"><div class="muted">Not Started</div><div class="kpi">${not}</div></div>`;overviewLegend.innerHTML=`<p>🟢 Completed: ${c}</p><p>🟠 Partial: ${partial}</p><p>🔴 Not Started: ${not}</p>`;quickSummary.innerHTML=`<div class="item"><b>Today Active Students</b><div class="kpi">${p.length}</div></div>`}
async function loadTargetStatus(){const dayId=targetDay.value||days[0]?.id;if(!dayId)return;const r=await sb.from("daily_progress").select("*,profiles(full_name)").eq("schedule_day_id",dayId);const rows=r.data||[];const c=rows.filter(x=>x.status==="completed").length,partial=rows.filter(x=>x.status==="partial").length,not=rows.filter(x=>x.status==="not_started").length;targetStatusCards.innerHTML=`<div class="kpi-card kpi-green span-4"><div class="muted">Completed</div><div class="kpi">${c}</div></div><div class="kpi-card kpi-orange span-4"><div class="muted">Partial</div><div class="kpi">${partial}</div></div><div class="kpi-card kpi-red span-4"><div class="muted">Not Started</div><div class="kpi">${not}</div></div>`;targetStatusBody.innerHTML=rows.map(x=>`<tr><td>${esc(x.profiles?.full_name||"")}</td><td>${x.completed_targets}/${x.total_targets}</td><td>${x.test_score_percent??"-"}%</td><td>${esc(x.status)}</td><td>${x.status==="completed"?"Excellent 🌹":x.status==="partial"?"Target पूरा करें ⚠️":"Work Complete नहीं हुआ ❌"}</td></tr>`).join("")}

function detectType(text){const t=text.toLowerCase();if(/अभिकथन|assertion/.test(t)&&/कारण|reason/.test(t))return"assertion_reason";if(/निष्कर्ष|conclusion/.test(t))return"statement_conclusion";if(/मिलान|सूची\s*[-–]?\s*i|list\s*[-–]?\s*i/.test(t))return"matching";if(/क्रमानुसार|सही क्रम|chronolog/.test(t))return"chronology";if(/रिक्त स्थान|____|fill in/.test(t))return"fill_blank";if(/सही कूट|correct code|कूट चुन/.test(t))return"correct_code";if(/विषम|odd one out/.test(t))return"odd_one_out";if(/कथनों? की सत्यता|कौन[- ]?से कथन सही|सही कथन/.test(t))return"multiple_statement_correctness";if(/(^|\n)\s*[1-9][.)]\s+/.test(text))return"multi_statement";return"normal_mcq"}
function answerIndex(raw){const s=(raw||"").trim().replace(/[()\[\]]/g,"").toUpperCase();const map={A:0,B:1,C:2,D:3,"क":0,"ख":1,"ग":2,"घ":3,"1":0,"2":1,"3":2,"4":3};return map[s]??null}
function parseRawQuestions(raw){
 const clean=raw.replace(/\r/g,"").trim();if(!clean)return[];
 const starts=[...clean.matchAll(/(?:^|\n)\s*(?:प्रश्न|Question|Q)\s*(?:No\.?\s*)?(\d+)\s*[.):-]?\s*/gi)];
 let blocks=[];
 if(starts.length){for(let i=0;i<starts.length;i++){const a=starts[i].index+(starts[i][0].startsWith("\n")?1:0),b=i+1<starts.length?starts[i+1].index:clean.length;blocks.push(clean.slice(a,b).trim())}}
 else blocks=clean.split(/\n\s*\n(?=\S)/).filter(Boolean);
 const out=[];
 for(const block0 of blocks){let block=block0.replace(/^\s*(?:प्रश्न|Question|Q)\s*(?:No\.?\s*)?\d+\s*[.):-]?\s*/i,"").trim();
  const ansM=block.match(/\n\s*(?:उत्तर|Answer|Ans\.?|सही उत्तर)\s*[:：-]\s*\(?\s*([A-Da-dकखगघ1-4])\s*\)?/i);if(!ansM)continue;
  const expM=block.match(/\n\s*(?:व्याख्या|Explanation|Solution)\s*[:：-]\s*([\s\S]*)$/i);
  const answer=answerIndex(ansM[1]);if(answer===null)continue;
  let content=block.slice(0,ansM.index).trim();
  const optRe=/(?:^|\n)\s*(?:\(([A-Da-dकखगघ])\)|([A-Da-dकखगघ])[.)])\s*([^\n]+)/g;
  const opts=[];let m;let first=-1;while((m=optRe.exec(content))){if(first<0)first=m.index+(m[0].startsWith("\n")?1:0);opts.push(m[3].trim())}
  if(opts.length!==4)continue;
  const qtext=(first>=0?content.slice(0,first):content).trim();
  out.push({question_type:detectType(qtext),question_text:qtext,options:opts,correct_answer:answer,explanation:expM?expM[1].trim():null});
 }
 return out;
}
async function publishRawTest(){const parsed=parseRawQuestions(rawQuestions.value);if(!parsed.length){toast("कोई valid question नहीं मिला। Format check करें।","error");return}const bad=parsed.find(q=>q.options.length!==4||q.correct_answer===null);if(bad){toast("कुछ प्रश्न सही parse नहीं हुए।","error");return}const tr=await sb.from("tests").insert({batch_id:APP_CONFIG.BATCH_ID,schedule_day_id:testDay.value||null,title:testName.value.trim()||"New Test",test_type:"daily",total_questions:parsed.length,total_marks:parsed.length,time_limit_minutes:+testTime.value||null,status:"published",created_by:adminUser.id}).select().single();if(tr.error){toast(tr.error.message,"error");return}for(let i=0;i<parsed.length;i++){const q=parsed[i];const rr=await sb.from("test_questions").insert({test_id:tr.data.id,question_order:i+1,marks:1,difficulty:"normal",question_type:q.question_type,question_text:q.question_text,options:q.options}).select().single();if(rr.error){toast("Question "+(i+1)+": "+rr.error.message,"error");return}const kr=await sb.from("test_question_keys").insert({question_id:rr.data.id,correct_answer:q.correct_answer,explanation:q.explanation});if(kr.error){toast(kr.error.message,"error");return}}toast(`${parsed.length} प्रश्नों का Test Publish हो गया।`,`success`);rawQuestions.value="";testName.value="";loadTests()}
async function loadTests(){const r=await sb.from("tests").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).order("created_at",{ascending:false});adminTests.innerHTML=(r.data||[]).map(t=>`<div class="item"><b>${esc(t.title)}</b><div class="muted">${t.total_questions} Questions • ${t.status}</div></div>`).join("")}

function parseOneLiners(raw){const lines=raw.replace(/\r/g,"").split("\n");const out=[];let q=null;for(const line0 of lines){const line=line0.trim();if(!line)continue;const qm=line.match(/^(?:प्रश्न|Question|Q)\s*(?:\d+)?\s*[.):-]?\s*(.+)$/i);const am=line.match(/^(?:उत्तर|Answer|Ans\.?)\s*[:：-]\s*(.+)$/i);if(qm){q=qm[1].trim()}else if(am&&q){out.push({question:q,answer:am[1].trim()});q=null}}return out}
async function publishOneLiners(){const rows=parseOneLiners(oneLinerRaw.value);if(!rows.length){toast("One-Liner format नहीं मिला।","error");return}const payload=rows.map(x=>({...x,subject:oneLinerSubject.value.trim()||null,status:"published",created_by:adminUser.id}));const r=await sb.from("one_liners").insert(payload);if(r.error){toast(r.error.message,"error");return}toast(`${rows.length} One-Liners Publish हो गए।`,`success`);oneLinerRaw.value="";loadOneLinersAdmin()}
async function loadOneLinersAdmin(){const r=await sb.from("one_liners").select("*").order("created_at",{ascending:false}).limit(100);adminOneLiners.innerHTML=(r.data||[]).map(x=>`<div class="item"><b>${esc(x.question)}</b><p>${esc(x.answer)}</p></div>`).join("")||'<div class="item">अभी कोई One-Liner नहीं है।</div>'}

async function loadVerificationTargets(){const dayId=pdfDay.value||days[0]?.id;if(!dayId)return;const r=await sb.from("daily_targets").select("*").eq("schedule_day_id",dayId).order("target_order");allTargets=r.data||[];verifyTarget.innerHTML=allTargets.map(t=>`<option value="${t.id}">${esc(t.subject)} — ${esc(t.topic)}</option>`).join("")}
pdfDay?.addEventListener?.("change",loadVerificationTargets);
async function createTargetVerification(){const target=allTargets.find(t=>t.id===verifyTarget.value);if(!target){toast("Target चुनें","error");return}const q=await sb.from("verification_questions").insert({schedule_day_id:target.schedule_day_id,target_id:target.id,verification_kind:verifyKind.value,question_text:verifyQuestion.value.trim(),answer_type:"text",is_active:true}).select().single();if(q.error){toast(q.error.message,"error");return}const k=await sb.from("verification_answer_keys").insert({verification_question_id:q.data.id,correct_answer:verifyAnswer.value.trim()});if(k.error){toast(k.error.message,"error");return}toast("Verification save हो गया","success");verifyQuestion.value="";verifyAnswer.value=""}
async function uploadPdf(){const f=pdfFile.files[0];if(!f){toast("PDF चुनें","error");return}if(f.size>25*1024*1024){toast("PDF 25 MB से बड़ी है","error");return}const path=`${pdfDay.value}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await sb.storage.from("study-pdfs").upload(path,f,{contentType:"application/pdf"});if(up.error){toast(up.error.message,"error");return}const ins=await sb.from("study_materials").insert({schedule_day_id:pdfDay.value,title:pdfTitle.value.trim()||f.name,material_type:"pdf",storage_path:path,file_size_bytes:f.size,mime_type:"application/pdf",status:"published",uploaded_by:adminUser.id,published_at:new Date().toISOString()});if(ins.error){toast(ins.error.message,"error");return}toast("PDF upload हो गई","success");loadMaterials()}
async function loadMaterials(){const r=await sb.from("study_materials").select("*,schedule_days(day_number)").order("created_at",{ascending:false});materialsList.innerHTML=(r.data||[]).map(m=>`<div class="item"><b>${esc(m.title)}</b><div class="muted">Day ${m.schedule_days?.day_number||"-"}</div></div>`).join("")}
async function loadReports(){const top=[...students].sort((a,b)=>(b.total_completed_days||0)-(a.total_completed_days||0)||(b.average_test_percentage||0)-(a.average_test_percentage||0)).slice(0,5);reportCards.innerHTML=`<div class="kpi-card kpi-green span-4"><div class="muted">Completed Days</div><div class="kpi">${students.reduce((a,s)=>a+(s.total_completed_days||0),0)}</div></div><div class="kpi-card kpi-blue span-4"><div class="muted">Students</div><div class="kpi">${students.length}</div></div><div class="kpi-card kpi-purple span-4"><div class="muted">Average Score</div><div class="kpi">${students.length?Math.round(students.reduce((a,s)=>a+(s.average_test_percentage||0),0)/students.length):0}%</div></div>`;topStudents.innerHTML=top.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.full_name||"")}</td><td>${s.total_completed_days||0}/125</td><td>${s.average_test_percentage||0}%</td></tr>`).join("")}
init();
