begin;

alter table public.schedule_days add column if not exists manual_lock boolean not null default false;
alter table public.schedule_days add column if not exists manual_unlock boolean not null default false;

create table if not exists public.broadcast_messages (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  message_type text not null default 'info',
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.student_notification_reads (
  id bigint generated by default as identity primary key,
  student_id uuid not null,
  broadcast_id bigint not null references public.broadcast_messages(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique(student_id,broadcast_id)
);

create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  notification_type text not null default 'info',
  related_type text,
  related_id text,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

alter table public.broadcast_messages enable row level security;
alter table public.student_notification_reads enable row level security;
alter table public.app_notifications enable row level security;

-- Read access for signed-in students/admins
create policy "broadcast read authenticated" on public.broadcast_messages for select to authenticated using (is_active = true);
create policy "notifications read authenticated" on public.app_notifications for select to authenticated using (is_active = true);
create policy "own notification reads" on public.student_notification_reads for select to authenticated using (student_id = auth.uid());
create policy "insert own notification reads" on public.student_notification_reads for insert to authenticated with check (student_id = auth.uid());

-- Admin write policies based on profiles.role
create policy "admin manage broadcasts" on public.broadcast_messages for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "admin manage notifications" on public.app_notifications for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

commit;
