begin;

-- ============================================================
-- GK BY PURUSHOTAM SIR - FULL AUDITED MASTER REPAIR
-- Idempotent: safe to run after previous project SQL patches.
-- ============================================================

-- ---------- Core columns ----------
alter table public.schedule_days add column if not exists manual_lock boolean not null default false;
alter table public.schedule_days add column if not exists manual_unlock boolean not null default false;

alter table public.verification_questions add column if not exists target_id uuid references public.daily_targets(id) on delete cascade;
alter table public.verification_questions add column if not exists show_question boolean not null default true;
alter table public.verification_questions add column if not exists explanation text;

alter table public.study_materials add column if not exists access_mode text not null default 'read_only';
alter table public.study_materials add column if not exists download_test_id uuid references public.tests(id) on delete set null;
alter table public.study_materials add column if not exists download_pass_percent numeric(5,2) not null default 80;
alter table public.study_materials add column if not exists requires_class_verification boolean not null default true;

alter table public.tests add column if not exists passing_percent numeric(5,2) not null default 0;
alter table public.tests add column if not exists is_final_daily boolean not null default false;
alter table public.tests add column if not exists is_pdf_download_gate boolean not null default false;
alter table public.tests add column if not exists allow_unlimited_retries boolean not null default true;

-- ---------- Topic-wise One-Liners ----------
create table if not exists public.one_liners (
  id uuid primary key default gen_random_uuid(),
  subject text,
  topic text,
  question text not null,
  answer text not null,
  status public.publication_status not null default 'published',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.one_liners add column if not exists topic text;
create index if not exists one_liners_subject_topic_idx on public.one_liners(subject,topic,created_at desc);
alter table public.one_liners enable row level security;

drop policy if exists "one_liners_student_select" on public.one_liners;
create policy "one_liners_student_select" on public.one_liners
for select to authenticated using(status='published' or public.is_admin());

drop policy if exists "one_liners_admin_all" on public.one_liners;
create policy "one_liners_admin_all" on public.one_liners
for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- ---------- Broadcast / In-app notifications ----------
create table if not exists public.broadcast_messages (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  message_type text not null default 'info',
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);
create table if not exists public.student_notification_reads (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  broadcast_id bigint not null references public.broadcast_messages(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique(student_id,broadcast_id)
);
create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  notification_type text not null default 'info',
  related_type text,
  related_id text,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

alter table public.broadcast_messages enable row level security;
alter table public.student_notification_reads enable row level security;
alter table public.app_notifications enable row level security;

drop policy if exists "broadcast_select" on public.broadcast_messages;
drop policy if exists "broadcast read authenticated" on public.broadcast_messages;
create policy "broadcast_select" on public.broadcast_messages
for select to authenticated using(is_active=true or public.is_admin());

drop policy if exists "broadcast_admin_all" on public.broadcast_messages;
drop policy if exists "admin manage broadcasts" on public.broadcast_messages;
create policy "broadcast_admin_all" on public.broadcast_messages
for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists "notification_reads_own" on public.student_notification_reads;
drop policy if exists "own notification reads" on public.student_notification_reads;
drop policy if exists "insert own notification reads" on public.student_notification_reads;
create policy "notification_reads_own" on public.student_notification_reads
for all to authenticated
using(student_id=auth.uid() or public.is_admin())
with check(student_id=auth.uid() or public.is_admin());

drop policy if exists "app_notifications_select" on public.app_notifications;
drop policy if exists "notifications read authenticated" on public.app_notifications;
create policy "app_notifications_select" on public.app_notifications
for select to authenticated using(is_active=true or public.is_admin());

drop policy if exists "app_notifications_admin_all" on public.app_notifications;
drop policy if exists "admin manage notifications" on public.app_notifications;
create policy "app_notifications_admin_all" on public.app_notifications
for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- ---------- Admin RPC: atomic verification replace ----------
create or replace function public.admin_replace_target_verifications(
  p_target_id uuid,
  p_schedule_day_id uuid,
  p_show_question boolean,
  p_items jsonb
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  item jsonb;
  qid uuid;
  n integer:=0;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' then raise exception 'Invalid verification data'; end if;

  delete from public.verification_questions
  where target_id=p_target_id and verification_kind='class';

  for item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.verification_questions(
      schedule_day_id,target_id,verification_kind,question_text,answer_type,options,
      show_question,is_active,explanation
    )
    values(
      p_schedule_day_id,p_target_id,'class',
      coalesce(nullif(item->>'question_text',''),'Class Verification'),
      'mcq',
      coalesce(item->'options','[]'::jsonb),
      coalesce(p_show_question,false),
      true,
      nullif(item->>'explanation','')
    )
    returning id into qid;

    insert into public.verification_answer_keys(verification_question_id,correct_answer,updated_at)
    values(qid,item->>'correct_answer',now())
    on conflict(verification_question_id)
    do update set correct_answer=excluded.correct_answer,updated_at=now();

    n:=n+1;
  end loop;
  return n;
end;
$$;
grant execute on function public.admin_replace_target_verifications(uuid,uuid,boolean,jsonb) to authenticated;

-- ---------- Admin RPC: bulk One-Liner publish ----------
create or replace function public.admin_publish_one_liners(
  p_subject text,
  p_topic text,
  p_items jsonb
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  item jsonb;
  n integer:=0;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' then raise exception 'Invalid One-Liner data'; end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    if nullif(trim(item->>'question'),'') is not null
       and nullif(trim(item->>'answer'),'') is not null then
      insert into public.one_liners(subject,topic,question,answer,status,created_by)
      values(
        coalesce(nullif(trim(p_subject),''),'General'),
        coalesce(nullif(trim(p_topic),''),'General'),
        trim(item->>'question'),
        trim(item->>'answer'),
        'published',
        auth.uid()
      );
      n:=n+1;
    end if;
  end loop;
  return n;
end;
$$;
grant execute on function public.admin_publish_one_liners(text,text,jsonb) to authenticated;

-- ---------- Verification: unlimited retry, target only after ALL verification questions correct ----------
create or replace function public.submit_target_verification(
  p_verification_question_id uuid,
  p_target_id uuid,
  p_answer text
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_correct text;
  v_ok boolean:=false;
  v_total integer:=0;
  v_correct_count integer:=0;
begin
  if v_user is null then raise exception 'Authentication required'; end if;

  select vak.correct_answer into v_correct
  from public.verification_questions vq
  join public.verification_answer_keys vak on vak.verification_question_id=vq.id
  where vq.id=p_verification_question_id
    and vq.target_id=p_target_id
    and vq.is_active=true;

  if v_correct is null then raise exception 'Verification question not configured'; end if;
  v_ok:=lower(trim(coalesce(p_answer,'')))=lower(trim(v_correct));

  insert into public.verification_attempts(user_id,verification_question_id,submitted_answer,is_correct,submitted_at)
  values(v_user,p_verification_question_id,p_answer,v_ok,now())
  on conflict(user_id,verification_question_id)
  do update set submitted_answer=excluded.submitted_answer,is_correct=excluded.is_correct,submitted_at=now();

  if v_ok then
    select count(*) into v_total
    from public.verification_questions
    where target_id=p_target_id and verification_kind='class' and is_active=true;

    select count(*) into v_correct_count
    from public.verification_questions vq
    join public.verification_attempts va
      on va.verification_question_id=vq.id
     and va.user_id=v_user
     and va.is_correct=true
    where vq.target_id=p_target_id
      and vq.verification_kind='class'
      and vq.is_active=true;

    if v_total>0 and v_correct_count>=v_total then
      insert into public.target_completions(user_id,target_id,is_completed,completion_source,completed_at)
      values(v_user,p_target_id,true,'verification',now())
      on conflict(user_id,target_id)
      do update set is_completed=true,completion_source='verification',completed_at=now();
    end if;
  end if;

  return v_ok;
end;
$$;
grant execute on function public.submit_target_verification(uuid,uuid,text) to authenticated;

-- ---------- PDF read gate ----------
create or replace function public.can_read_material(p_material_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  m public.study_materials;
  total_required integer:=0;
  completed_required integer:=0;
begin
  if auth.uid() is null then return false; end if;
  select * into m from public.study_materials where id=p_material_id and status='published';
  if m.id is null then return false; end if;
  if coalesce(m.requires_class_verification,false)=false then return true; end if;

  select count(*) into total_required
  from public.daily_targets
  where schedule_day_id=m.schedule_day_id and is_required=true and status='published';

  select count(*) into completed_required
  from public.target_completions tc
  join public.daily_targets dt on dt.id=tc.target_id
  where tc.user_id=auth.uid()
    and tc.is_completed=true
    and dt.schedule_day_id=m.schedule_day_id
    and dt.is_required=true
    and dt.status='published';

  return total_required=0 or completed_required>=total_required;
end;
$$;
grant execute on function public.can_read_material(uuid) to authenticated;

-- ---------- Secure PDF download gate ----------
create or replace function public.can_download_material(p_material_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  m public.study_materials;
  best_score numeric(5,2);
  can_read boolean;
begin
  if auth.uid() is null then return false; end if;
  select * into m from public.study_materials where id=p_material_id and status='published';
  if m.id is null then return false; end if;

  select public.can_read_material(p_material_id) into can_read;
  if not can_read then return false; end if;

  if m.access_mode='direct_download' then return true; end if;
  if m.access_mode='read_only' then return false; end if;
  if m.access_mode='test_required' and m.download_test_id is not null then
    select max(percentage) into best_score
    from public.test_attempts
    where user_id=auth.uid() and test_id=m.download_test_id and status='submitted';
    return coalesce(best_score,0)>=coalesce(m.download_pass_percent,80);
  end if;
  return false;
end;
$$;
grant execute on function public.can_download_material(uuid) to authenticated;

-- ---------- Review answers only after passing ----------
create or replace function public.get_attempt_review(p_attempt_id uuid)
returns table(
  question_id uuid,question_order int,question_type public.question_type,question_text text,
  options jsonb,selected_answer jsonb,correct_answer jsonb,is_correct boolean,is_skipped boolean,
  explanation text,subject text,topic text
)
language plpgsql
security definer
set search_path=public
as $$
declare
  allowed boolean:=false;
begin
  select exists(
    select 1
    from public.test_attempts ta
    join public.tests t on t.id=ta.test_id
    where ta.id=p_attempt_id
      and ta.status='submitted'
      and (ta.user_id=auth.uid() or public.is_admin())
      and (public.is_admin() or coalesce(ta.percentage,0)>=coalesce(t.passing_percent,0))
  ) into allowed;

  if not allowed then
    raise exception 'Question review unlocks only after passing score is achieved';
  end if;

  return query
  select q.id,q.question_order,q.question_type,q.question_text,q.options,a.selected_answer,k.correct_answer,
         coalesce(a.is_correct,false),coalesce(a.is_skipped,true),k.explanation,q.subject,q.topic
  from public.test_attempts ta
  join public.test_questions q on q.test_id=ta.test_id
  left join public.test_answers a on a.attempt_id=ta.id and a.question_id=q.id
  join public.test_question_keys k on k.question_id=q.id
  where ta.id=p_attempt_id
  order by q.question_order;
end;
$$;
grant execute on function public.get_attempt_review(uuid) to authenticated;

-- ---------- Final daily completion gate ----------
create or replace function public.refresh_daily_progress(p_user_id uuid,p_schedule_day_id uuid)
returns public.daily_progress
language plpgsql
security definer
set search_path=public
as $$
declare
  tt int:=0; ct int:=0;
  final_test_id uuid; final_pass numeric(5,2):=0; best_final numeric(5,2):=null;
  st public.progress_status; fb public.feedback_code; rowout public.daily_progress;
begin
  if not(p_user_id=auth.uid() or public.is_admin()) then raise exception 'Access denied'; end if;

  select count(*) into tt
  from public.daily_targets
  where schedule_day_id=p_schedule_day_id and is_required=true and status='published';

  select count(*) into ct
  from public.target_completions tc
  join public.daily_targets dt on dt.id=tc.target_id
  where tc.user_id=p_user_id and tc.is_completed=true
    and dt.schedule_day_id=p_schedule_day_id and dt.is_required=true and dt.status='published';

  select id,passing_percent into final_test_id,final_pass
  from public.tests
  where schedule_day_id=p_schedule_day_id and status='published' and is_final_daily=true
  order by created_at desc limit 1;

  if final_test_id is not null then
    select max(percentage) into best_final
    from public.test_attempts
    where user_id=p_user_id and test_id=final_test_id and status='submitted';
  end if;

  if ct=0 and best_final is null then
    st:='not_started'; fb:='work_not_started';
  elsif ct<tt then
    st:='partial'; fb:='target_pending';
  elsif final_test_id is not null and coalesce(best_final,0)<coalesce(final_pass,0) then
    st:='partial'; fb:='test_pending';
  else
    st:='completed';
    if coalesce(best_final,100)>=80 then fb:='excellent'; else fb:='very_good'; end if;
  end if;

  insert into public.daily_progress(
    user_id,schedule_day_id,total_targets,completed_targets,class_verified,pdf_verified,
    test_submitted,test_score_percent,status,feedback,updated_at
  )
  values(
    p_user_id,p_schedule_day_id,tt,ct,ct=tt,false,best_final is not null,best_final,st,fb,now()
  )
  on conflict(user_id,schedule_day_id) do update set
    total_targets=excluded.total_targets,
    completed_targets=excluded.completed_targets,
    class_verified=excluded.class_verified,
    test_submitted=excluded.test_submitted,
    test_score_percent=excluded.test_score_percent,
    status=excluded.status,
    feedback=excluded.feedback,
    updated_at=now()
  returning * into rowout;

  return rowout;
end;
$$;
grant execute on function public.refresh_daily_progress(uuid,uuid) to authenticated;

commit;


-- ===== ADMIN DELETE CONTROLS =====

create or replace function public.admin_delete_one_liner(p_one_liner_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from one_liners where id=p_one_liner_id;
end $$;

create or replace function public.admin_delete_one_liner_topic(p_subject text,p_topic text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from one_liners where subject=p_subject and topic=p_topic;
end $$;

create or replace function public.admin_delete_all_one_liners()
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from one_liners;
end $$;

create or replace function public.admin_delete_test_question(p_question_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from test_questions where id=p_question_id;
end $$;

create or replace function public.admin_delete_test(p_test_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from test_questions where test_id=p_test_id;
  delete from test_attempts where test_id=p_test_id;
  delete from tests where id=p_test_id;
end $$;

create or replace function public.admin_delete_all_tests()
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from test_questions;
  delete from test_attempts;
  delete from tests;
end $$;

create or replace function public.admin_delete_material(p_material_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from study_materials where id=p_material_id;
end $$;

create or replace function public.admin_delete_all_materials()
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from profiles p where p.id=auth.uid() and p.role::text='admin') then
    raise exception 'Admin only';
  end if;
  delete from study_materials;
end $$;

grant execute on function public.admin_delete_one_liner(uuid) to authenticated;
grant execute on function public.admin_delete_one_liner_topic(text,text) to authenticated;
grant execute on function public.admin_delete_all_one_liners() to authenticated;
grant execute on function public.admin_delete_test_question(uuid) to authenticated;
grant execute on function public.admin_delete_test(uuid) to authenticated;
grant execute on function public.admin_delete_all_tests() to authenticated;
grant execute on function public.admin_delete_material(uuid) to authenticated;
grant execute on function public.admin_delete_all_materials() to authenticated;
