-- GK BY PURUSHOTAM SIR — V12 Subject/Topic Sync (203 Topics)
-- इसे नए Turso database gk-mock-test-production में एक बार चलाएँ।

INSERT INTO cbt_subjects(subject_key,subject_name,display_order,active) VALUES
('haryana_gk','Haryana GK',1,1),
('indian_history','History',2,1),
('indian_polity','Polity',3,1),
('indian_geography','Geography',4,1),
('science','Science',5,1),
('indian_static_gk','Static GK',6,1),
('indian_economy','Economy',7,1),
('computer','Computer',8,1),
('current_affairs','Current Affairs',9,1)
ON CONFLICT(subject_key) DO UPDATE SET subject_name=excluded.subject_name,display_order=excluded.display_order,active=1;

INSERT INTO cbt_topics(subject_key,topic_key,topic_name,display_order,active) VALUES
('haryana_gk','haryana_parichay','हरियाणा का परिचय',1,0),
('haryana_gk','haryana_namkaran','हरियाणा का नामकरण',2,0),
('haryana_gk','haryana_gathan_punargathan','हरियाणा का गठन एवं पुनर्गठन',3,0),
('haryana_gk','haryana_bhaugolik_sthiti','हरियाणा की भौगोलिक स्थिति',4,0),
('haryana_gk','haryana_seemayen_padosi_rajya','हरियाणा की सीमाएँ और पड़ोसी राज्य',5,0),
('haryana_gk','haryana_prashasanik_dhancha','हरियाणा का प्रशासनिक ढांचा',6,0),
('haryana_gk','haryana_mandal_tahsil_uptahsil_block','हरियाणा के मंडल, तहसील, उप-तहसील और ब्लॉक',7,0),
('haryana_gk','haryana_vidhansabha_loksabha_rajyasabha','हरियाणा की विधानसभा, लोकसभा और राज्यसभा',8,0),
('haryana_gk','haryana_pratham','हरियाणा के प्रथम',9,0),
('haryana_gk','haryana_sabse_bade_chhote_tathya','हरियाणा के सबसे बड़े/छोटे तथ्य',10,0),
('haryana_gk','haryana_upnaam','हरियाणा के उपनाम',11,0),
('haryana_gk','haryana_janganana','हरियाणा की जनगणना',12,0),
('haryana_gk','haryana_saksharta','हरियाणा की साक्षरता',13,0),
('haryana_gk','haryana_nadiyan','हरियाणा की नदियाँ',14,0),
('haryana_gk','haryana_naharen','हरियाणा की नहरें',15,0),
('haryana_gk','haryana_sinchai_pariyojanayen','हरियाणा की सिंचाई परियोजनाएँ',16,0),
('haryana_gk','haryana_jheelen','हरियाणा की झीलें',17,0),
('haryana_gk','haryana_jalvayu','हरियाणा की जलवायु',18,0),
('haryana_gk','haryana_mittiyan','हरियाणा की मिट्टियाँ',19,0),
('haryana_gk','haryana_krishi','हरियाणा की कृषि',20,0),
('haryana_gk','haryana_pashupalan_vyavastha','हरियाणा की पशुपालन व्यवस्था',21,0),
('haryana_gk','haryana_van','हरियाणा के वन',22,0),
('haryana_gk','haryana_vanyajeev_abhayaaranya','हरियाणा के वन्यजीव और अभयारण्य',23,0),
('haryana_gk','haryana_khanij','हरियाणा के खनिज',24,0),
('haryana_gk','haryana_urja','हरियाणा की ऊर्जा',25,0),
('haryana_gk','haryana_arthvyavastha','हरियाणा की अर्थव्यवस्था',26,0),
('haryana_gk','haryana_udyog','हरियाणा के उद्योग',27,0),
('haryana_gk','haryana_sadak_rail_hawai_vyavastha','हरियाणा की सड़क, रेल और हवाई व्यवस्था',28,0),
('haryana_gk','haryana_vishwavidyalay_shaikshanik_sansthan','हरियाणा के विश्वविद्यालय और शिक्षण संस्थान',29,0),
('haryana_gk','haryana_prachin_itihas','हरियाणा का प्राचीन इतिहास',30,0),
('haryana_gk','haryana_madhyakalin_itihas','हरियाणा का मध्यकालीन इतिहास',31,0),
('haryana_gk','haryana_aadhunik_itihas','हरियाणा का आधुनिक इतिहास',32,0),
('haryana_gk','haryana_mahabharat_kaal','हरियाणा और महाभारत काल',33,0),
('haryana_gk','haryana_puratatvik_sthal','हरियाणा के पुरातात्विक स्थल',34,0),
('haryana_gk','haryana_pramukh_yuddh','हरियाणा के प्रमुख युद्ध',35,0),
('haryana_gk','haryana_andolan','हरियाणा के आंदोलन',36,0),
('haryana_gk','haryana_1857_ki_kranti','हरियाणा में 1857 की क्रांति',37,0),
('haryana_gk','haryana_arya_samaj_samajik_sudhar_andolan','हरियाणा में आर्य समाज और सामाजिक सुधार आंदोलन',38,0),
('haryana_gk','haryana_riyasaten','हरियाणा की रियासतें',39,0),
('haryana_gk','haryana_mukhyamantri','हरियाणा के मुख्यमंत्री',40,0),
('haryana_gk','haryana_rajyapal','हरियाणा के राज्यपाल',41,0),
('haryana_gk','haryana_nyay_vyavastha','हरियाणा की न्याय व्यवस्था',42,0),
('haryana_gk','haryana_pramukh_yojanayen','हरियाणा की प्रमुख योजनाएँ',43,0),
('haryana_gk','haryana_dharmik_sthal','हरियाणा के धार्मिक स्थल',44,0),
('haryana_gk','haryana_paryatan_sthal','हरियाणा के पर्यटन स्थल',45,0),
('haryana_gk','haryana_aitihasik_sthal','हरियाणा के ऐतिहासिक स्थल',46,0),
('haryana_gk','haryana_mele','हरियाणा के मेले',47,0),
('haryana_gk','haryana_tyohar','हरियाणा के त्योहार',48,0),
('haryana_gk','haryana_lok_sanskriti','हरियाणा की लोक संस्कृति',49,0),
('haryana_gk','haryana_lokgeet','हरियाणा के लोकगीत',50,0),
('haryana_gk','haryana_lok_nritya','हरियाणा के लोक नृत्य',51,0),
('haryana_gk','haryana_saang_loknatya','हरियाणा का सांग और लोकनाट्य',52,0),
('haryana_gk','haryana_vaadya_yantra','हरियाणा के वाद्य यंत्र',53,0),
('haryana_gk','haryana_pahanava_aabhushan','हरियाणा का पहनावा और आभूषण',54,0),
('haryana_gk','haryana_khan_paan','हरियाणा का खान-पान',55,0),
('haryana_gk','haryana_patr_patrikayen','हरियाणा की पत्र-पत्रिकाएँ',56,0),
('haryana_gk','haryana_pramukh_lekhak_kavi','हरियाणा के प्रमुख लेखक और कवि',57,0),
('haryana_gk','haryana_prasiddh_hastiyan','हरियाणा की प्रसिद्ध हस्तियाँ',58,0),
('haryana_gk','haryana_khiladi','हरियाणा के खिलाड़ी',59,0),
('haryana_gk','haryana_khel_stadium','हरियाणा के खेल और स्टेडियम',60,0),
('haryana_gk','haryana_puraskar_samman','हरियाणा के पुरस्कार और सम्मान',61,0),
('haryana_gk','haryana_mool_ke_rashtriya_vyaktitva','हरियाणा मूल के राष्ट्रीय व्यक्तित्व',62,0),
('haryana_gk','haryana_mool_ke_anya_rajyon_ke_mukhyamantri','हरियाणा मूल के अन्य राज्यों के मुख्यमंत्री',63,0),
('haryana_gk','haryana_mahilayen_upalabdhiyan','हरियाणा की महिलाएँ और उपलब्धियाँ',64,0),
('haryana_gk','haryana_pramukh_mandir','हरियाणा के प्रमुख मंदिर',65,0),
('haryana_gk','haryana_pramukh_gurudware_masjid_anya_dharmik_sthal','हरियाणा के प्रमुख गुरुद्वारे, मस्जिद और अन्य धार्मिक स्थल',66,0),
('haryana_gk','haryana_samasamayiki_current_affairs','हरियाणा समसामयिकी / हरियाणा करंट अफेयर्स',67,0),
('haryana_gk','haryana_gk_one_liner_facts','हरियाणा GK One Liner Facts',68,0),
('haryana_gk','haryana_gk_milan_prashn','हरियाणा GK मिलान प्रश्न',69,0),
('haryana_gk','haryana_gk_kramanusar_prashn','हरियाणा GK क्रमानुसार प्रश्न',70,0),
('haryana_gk','haryana_gk_kathan_nishkarsh','हरियाणा GK कथन-निष्कर्ष',71,0),
('haryana_gk','haryana_gk_khali_sthan_bharo','हरियाणा GK खाली स्थान भरो',72,0),
('haryana_gk','haryana_gk_mahatvapurn_varsh_tithiyan','हरियाणा GK महत्वपूर्ण वर्ष और तिथियाँ',73,0),
('haryana_gk','vividh','विविध',74,0),
('indian_history','history_sources','इतिहास के स्रोत और काल-विभाजन',1,0),
('indian_history','prehistory','प्रागैतिहासिक काल',2,0),
('indian_history','indus_valley','सिंधु घाटी सभ्यता',3,0),
('indian_history','vedic_age','वैदिक काल',4,0),
('indian_history','mahajanapadas','महाजनपद काल',5,0),
('indian_history','jainism_buddhism','जैन धर्म और बौद्ध धर्म',6,0),
('indian_history','mauryan_empire','मौर्य साम्राज्य',7,0),
('indian_history','post_mauryan','उत्तर-मौर्य काल',8,0),
('indian_history','gupta_age','गुप्त काल',9,0),
('indian_history','ancient_south_india','प्राचीन दक्षिण भारत',10,0),
('indian_history','early_medieval_india','प्रारंभिक मध्यकालीन भारत',11,0),
('indian_history','delhi_sultanate','दिल्ली सल्तनत',12,0),
('indian_history','vijayanagara_bahmani','विजयनगर और बहमनी राज्य',13,0),
('indian_history','mughal_empire','मुगल साम्राज्य',14,0),
('indian_history','maratha_history','मराठा इतिहास',15,0),
('indian_history','european_arrival','भारत में यूरोपीय शक्तियों का आगमन',16,0),
('indian_history','company_rule_expansion','ईस्ट इंडिया कंपनी का विस्तार',17,0),
('indian_history','revolt_1857','1857 की क्रांति',18,0),
('indian_history','social_religious_reform','सामाजिक और धार्मिक सुधार आंदोलन',19,0),
('indian_history','freedom_movement','भारतीय राष्ट्रीय आंदोलन और स्वतंत्रता',20,0),
('indian_polity','constitutional_history','भारतीय संविधान का ऐतिहासिक विकास',1,0),
('indian_polity','constituent_assembly','संविधान सभा और संविधान निर्माण',2,0),
('indian_polity','preamble','संविधान की प्रस्तावना',3,0),
('indian_polity','citizenship','नागरिकता',4,0),
('indian_polity','fundamental_rights','मौलिक अधिकार',5,0),
('indian_polity','directive_principles','राज्य के नीति-निर्देशक तत्व',6,0),
('indian_polity','fundamental_duties','मौलिक कर्तव्य',7,0),
('indian_polity','president_vice_president','राष्ट्रपति और उपराष्ट्रपति',8,0),
('indian_polity','prime_minister_council','प्रधानमंत्री और मंत्रिपरिषद',9,0),
('indian_polity','parliament','संसद',10,0),
('indian_polity','supreme_court','सर्वोच्च न्यायालय',11,0),
('indian_polity','high_court_subordinate','उच्च न्यायालय और अधीनस्थ न्यायालय',12,0),
('indian_polity','centre_state_relations','केंद्र-राज्य संबंध',13,0),
('indian_polity','emergency_provisions','आपातकालीन प्रावधान',14,0),
('indian_polity','constitutional_bodies','संवैधानिक निकाय',15,0),
('indian_polity','non_constitutional_bodies','गैर-संवैधानिक निकाय',16,0),
('indian_polity','local_self_government','पंचायती राज और नगरीय शासन',17,0),
('indian_polity','amendments_schedules_elections','संशोधन, अनुसूचियाँ, चुनाव और दल-बदल',18,0),
('indian_geography','earth_universe','पृथ्वी और ब्रह्मांड',1,0),
('indian_geography','latitude_longitude_time','अक्षांश, देशांतर और समय',2,0),
('indian_geography','geomorphology','भू-आकृति विज्ञान',3,0),
('indian_geography','climatology','जलवायु विज्ञान',4,0),
('indian_geography','oceanography','महासागर विज्ञान',5,0),
('indian_geography','world_physical_geography','विश्व का भौतिक भूगोल',6,0),
('indian_geography','india_physiography','भारत का भौतिक स्वरूप',7,0),
('indian_geography','india_drainage','भारत की नदियाँ और अपवाह तंत्र',8,0),
('indian_geography','india_climate','भारत की जलवायु',9,0),
('indian_geography','india_soils','भारत की मिट्टियाँ',10,0),
('indian_geography','natural_vegetation_wildlife','प्राकृतिक वनस्पति और वन्यजीव',11,0),
('indian_geography','indian_agriculture','भारतीय कृषि',12,0),
('indian_geography','minerals_energy','खनिज और ऊर्जा संसाधन',13,0),
('indian_geography','industries','उद्योग',14,0),
('indian_geography','transport_communication','परिवहन और संचार',15,0),
('indian_geography','population_settlement','जनसंख्या और मानव बस्तियाँ',16,0),
('indian_geography','environment_ecology','पर्यावरण और पारिस्थितिकी',17,0),
('indian_geography','disaster_management','प्राकृतिक आपदाएँ और आपदा प्रबंधन',18,0),
('science','units_measurement','मात्रक और मापन',1,0),
('science','motion_laws','गति और गति के नियम',2,0),
('science','work_energy_power','कार्य, ऊर्जा और शक्ति',3,0),
('science','gravitation','गुरुत्वाकर्षण',4,0),
('science','heat_temperature','ऊष्मा और तापमान',5,0),
('science','waves_sound','तरंग और ध्वनि',6,0),
('science','light_optics','प्रकाश और प्रकाशिकी',7,0),
('science','electricity','विद्युत',8,0),
('science','magnetism','चुंबकत्व',9,0),
('science','atomic_nuclear_physics','परमाणु और नाभिकीय भौतिकी',10,0),
('science','matter_atom_molecule','पदार्थ, परमाणु और अणु',11,0),
('science','chemical_reactions','रासायनिक अभिक्रियाएँ',12,0),
('science','acids_bases_salts','अम्ल, क्षार और लवण',13,0),
('science','metals_nonmetals','धातु और अधातु',14,0),
('science','carbon_compounds','कार्बन और उसके यौगिक',15,0),
('science','periodic_table','आवर्त सारणी',16,0),
('science','cell_biology','कोशिका विज्ञान',17,0),
('science','human_body_systems','मानव शरीर तंत्र',18,0),
('science','plant_biology','पादप विज्ञान',19,0),
('science','genetics_evolution','आनुवंशिकी और विकास',20,0),
('science','microorganisms_diseases','सूक्ष्मजीव और रोग',21,0),
('science','nutrition_health','पोषण और स्वास्थ्य',22,0),
('science','ecology_pollution','पारिस्थितिकी और प्रदूषण',23,0),
('science','everyday_science_space_biotech','दैनिक जीवन विज्ञान, अंतरिक्ष और जैव-प्रौद्योगिकी',24,0),
('indian_static_gk','books_authors','पुस्तकें और लेखक',1,0),
('indian_static_gk','awards_honours','पुरस्कार और सम्मान',2,0),
('indian_static_gk','sports_games','खेल और प्रतियोगिताएँ',3,0),
('indian_static_gk','art_culture','भारतीय कला और संस्कृति',4,0),
('indian_static_gk','dances','लोक और शास्त्रीय नृत्य',5,0),
('indian_static_gk','music_instruments','संगीत और वाद्य यंत्र',6,0),
('indian_static_gk','festivals_fairs','त्योहार और मेले',7,0),
('indian_static_gk','religions_philosophy','धर्म और दर्शन',8,0),
('indian_static_gk','monuments_world_heritage','स्मारक और विश्व धरोहर स्थल',9,0),
('indian_static_gk','national_symbols','राष्ट्रीय प्रतीक',10,0),
('indian_static_gk','organizations_headquarters','राष्ट्रीय-अंतरराष्ट्रीय संगठन और मुख्यालय',11,0),
('indian_static_gk','important_days_themes','महत्वपूर्ण दिवस और विषय',12,0),
('indian_static_gk','firsts_superlatives','भारत और विश्व के प्रथम एवं सबसे बड़े-छोटे',13,0),
('indian_static_gk','countries_capitals_currencies','देश, राजधानी और मुद्रा',14,0),
('indian_static_gk','borders_places','सीमाएँ, दर्रे और महत्वपूर्ण स्थान',15,0),
('indian_static_gk','misc_static_gk','विविध Static GK',16,0),
('indian_economy','basic_economics','अर्थशास्त्र की मूल अवधारणाएँ',1,0),
('indian_economy','national_income','राष्ट्रीय आय',2,0),
('indian_economy','planning_niti_aayog','योजना और नीति आयोग',3,0),
('indian_economy','banking_rbi','बैंकिंग और भारतीय रिजर्व बैंक',4,0),
('indian_economy','money_inflation','मुद्रा और मुद्रास्फीति',5,0),
('indian_economy','budget_taxation','बजट और कर व्यवस्था',6,0),
('indian_economy','public_finance','लोक वित्त',7,0),
('indian_economy','agriculture_economy','कृषि अर्थव्यवस्था',8,0),
('indian_economy','industry_infrastructure','उद्योग और आधारभूत संरचना',9,0),
('indian_economy','external_sector','विदेश व्यापार और भुगतान संतुलन',10,0),
('indian_economy','poverty_unemployment','गरीबी और बेरोजगारी',11,0),
('indian_economy','government_schemes_economy','आर्थिक सर्वेक्षण और सरकारी योजनाएँ',12,0),
('computer','computer_fundamentals','कंप्यूटर की मूल बातें',1,0),
('computer','hardware','कंप्यूटर हार्डवेयर',2,0),
('computer','software_operating_system','सॉफ्टवेयर और ऑपरेटिंग सिस्टम',3,0),
('computer','memory_storage','मेमोरी और स्टोरेज',4,0),
('computer','input_output_devices','इनपुट और आउटपुट डिवाइस',5,0),
('computer','ms_office','MS Office',6,0),
('computer','internet_web','इंटरनेट और वेब',7,0),
('computer','networking','कंप्यूटर नेटवर्किंग',8,0),
('computer','cyber_security','साइबर सुरक्षा',9,0),
('computer','computer_abbreviations','कंप्यूटर संक्षिप्तियाँ और विविध तथ्य',10,0),
('current_affairs','national_current_affairs','राष्ट्रीय समसामयिकी',1,0),
('current_affairs','international_current_affairs','अंतरराष्ट्रीय समसामयिकी',2,0),
('current_affairs','haryana_current_affairs','हरियाणा समसामयिकी',3,0),
('current_affairs','economy_current_affairs','अर्थव्यवस्था समसामयिकी',4,0),
('current_affairs','science_technology_current','विज्ञान और प्रौद्योगिकी समसामयिकी',5,0),
('current_affairs','environment_current','पर्यावरण समसामयिकी',6,0),
('current_affairs','sports_current','खेल समसामयिकी',7,0),
('current_affairs','awards_appointments','पुरस्कार और नियुक्तियाँ',8,0),
('current_affairs','reports_indexes','रिपोर्ट और सूचकांक',9,0),
('current_affairs','defence_current','रक्षा समसामयिकी',10,0),
('current_affairs','monthly_current_revision','मासिक समसामयिकी पुनरावृत्ति',11,0)
ON CONFLICT(subject_key,topic_key) DO UPDATE SET topic_name=excluded.topic_name,display_order=excluded.display_order;
