begin;

-- ============================================================
-- GK BY PURUSHOTAM SIR - 6 MONTHS ULTIMATE WORKFLOW PATCH
-- Run once after previous setup/patches.
-- ============================================================

-- Student should never see full roadmap: frontend only loads current unlocked day.
-- Automatic date unlock + manual admin override.
alter table public.schedule_days add column if not exists manual_lock boolean not null default false;
alter table public.schedule_days add column if not exists manual_unlock boolean not null default false;

-- Verification: Admin can hide question and show only options.
alter table public.verification_questions add column if not exists show_question boolean not null default true;
alter table public.verification_questions add column if not exists target_id uuid references public.daily_targets(id) on delete cascade;

-- PDF access controls.
alter table public.study_materials add column if not exists access_mode text not null default 'read_only';
alter table public.study_materials add column if not exists download_test_id uuid references public.tests(id) on delete set null;
alter table public.study_materials add column if not exists download_pass_percent numeric(5,2) not null default 80;
alter table public.study_materials add column if not exists requires_class_verification boolean not null default true;

-- Test controls.
alter table public.tests add column if not exists passing_percent numeric(5,2) not null default 0;
alter table public.tests add column if not exists is_final_daily boolean not null default false;
alter table public.tests add column if not exists is_pdf_download_gate boolean not null default false;
alter table public.tests add column if not exists allow_unlimited_retries boolean not null default true;

-- Topic-wise One-Liners.
alter table public.one_liners add column if not exists topic text;
create index if not exists one_liners_subject_topic_idx on public.one_liners(subject,topic,created_at desc);

-- Broadcast + in-app notifications.
create table if not exists public.broadcast_messages (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  message_type text not null default 'info',
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);
create table if not exists public.student_notification_reads (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  broadcast_id bigint not null references public.broadcast_messages(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique(student_id,broadcast_id)
);
create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  notification_type text not null default 'info',
  related_type text,
  related_id text,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

alter table public.broadcast_messages enable row level security;
alter table public.student_notification_reads enable row level security;
alter table public.app_notifications enable row level security;

drop policy if exists "broadcast_select" on public.broadcast_messages;
create policy "broadcast_select" on public.broadcast_messages for select to authenticated using(is_active=true or public.is_admin());
drop policy if exists "broadcast_admin_all" on public.broadcast_messages;
create policy "broadcast_admin_all" on public.broadcast_messages for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists "notification_reads_own" on public.student_notification_reads;
create policy "notification_reads_own" on public.student_notification_reads for all to authenticated using(student_id=auth.uid() or public.is_admin()) with check(student_id=auth.uid() or public.is_admin());

drop policy if exists "app_notifications_select" on public.app_notifications;
create policy "app_notifications_select" on public.app_notifications for select to authenticated using(is_active=true or public.is_admin());
drop policy if exists "app_notifications_admin_all" on public.app_notifications;
create policy "app_notifications_admin_all" on public.app_notifications for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Verification submission: unlimited retries; correct answer completes target.
create or replace function public.submit_target_verification(
  p_verification_question_id uuid,
  p_target_id uuid,
  p_answer text
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_correct text;
  v_ok boolean:=false;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  select vak.correct_answer into v_correct
  from public.verification_questions vq
  join public.verification_answer_keys vak on vak.verification_question_id=vq.id
  where vq.id=p_verification_question_id and vq.target_id=p_target_id and vq.is_active=true;
  if v_correct is null then raise exception 'Verification question not configured'; end if;
  v_ok:=lower(trim(coalesce(p_answer,'')))=lower(trim(v_correct));
  insert into public.verification_attempts(user_id,verification_question_id,submitted_answer,is_correct,submitted_at)
  values(v_user,p_verification_question_id,p_answer,v_ok,now())
  on conflict(user_id,verification_question_id)
  do update set submitted_answer=excluded.submitted_answer,is_correct=excluded.is_correct,submitted_at=now();
  if v_ok then
    insert into public.target_completions(user_id,target_id,is_completed,completion_source,completed_at)
    values(v_user,p_target_id,true,'verification',now())
    on conflict(user_id,target_id)
    do update set is_completed=true,completion_source='verification',completed_at=now();
  end if;
  return v_ok;
end; $$;
grant execute on function public.submit_target_verification(uuid,uuid,text) to authenticated;

-- Eligibility check for secure PDF download.
create or replace function public.can_download_material(p_material_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  m public.study_materials;
  best_score numeric(5,2);
begin
  if auth.uid() is null then return false; end if;
  select * into m from public.study_materials where id=p_material_id and status='published';
  if m.id is null then return false; end if;
  if m.access_mode='direct_download' then return true; end if;
  if m.access_mode='read_only' then return false; end if;
  if m.access_mode='test_required' and m.download_test_id is not null then
    select max(percentage) into best_score from public.test_attempts
    where user_id=auth.uid() and test_id=m.download_test_id and status='submitted';
    return coalesce(best_score,0)>=coalesce(m.download_pass_percent,80);
  end if;
  return false;
end; $$;
grant execute on function public.can_download_material(uuid) to authenticated;

-- Daily completion requires all required target verifications AND final daily test pass if configured.
create or replace function public.refresh_daily_progress(p_user_id uuid,p_schedule_day_id uuid)
returns public.daily_progress
language plpgsql
security definer
set search_path=public
as $$
declare
  tt int:=0; ct int:=0;
  final_test_id uuid; final_pass numeric(5,2):=0; best_final numeric(5,2):=null;
  st public.progress_status; fb public.feedback_code; rowout public.daily_progress;
begin
  if not(p_user_id=auth.uid() or public.is_admin()) then raise exception 'Access denied'; end if;
  select count(*) into tt from public.daily_targets where schedule_day_id=p_schedule_day_id and is_required=true and status='published';
  select count(*) into ct from public.target_completions tc join public.daily_targets dt on dt.id=tc.target_id
  where tc.user_id=p_user_id and tc.is_completed=true and dt.schedule_day_id=p_schedule_day_id and dt.is_required=true;

  select id,passing_percent into final_test_id,final_pass from public.tests
  where schedule_day_id=p_schedule_day_id and status='published' and is_final_daily=true
  order by created_at desc limit 1;
  if final_test_id is not null then
    select max(percentage) into best_final from public.test_attempts
    where user_id=p_user_id and test_id=final_test_id and status='submitted';
  end if;

  if ct=0 and best_final is null then st:='not_started'; fb:='work_not_started';
  elsif ct<tt then st:='partial'; fb:='target_pending';
  elsif final_test_id is not null and coalesce(best_final,0)<coalesce(final_pass,0) then st:='partial'; fb:='test_pending';
  else st:='completed'; if coalesce(best_final,100)>=80 then fb:='excellent'; else fb:='very_good'; end if;
  end if;

  insert into public.daily_progress(user_id,schedule_day_id,total_targets,completed_targets,class_verified,pdf_verified,test_submitted,test_score_percent,status,feedback,updated_at)
  values(p_user_id,p_schedule_day_id,tt,ct,ct=tt,false,best_final is not null,best_final,st,fb,now())
  on conflict(user_id,schedule_day_id) do update set
    total_targets=excluded.total_targets,completed_targets=excluded.completed_targets,class_verified=excluded.class_verified,
    test_submitted=excluded.test_submitted,test_score_percent=excluded.test_score_percent,status=excluded.status,feedback=excluded.feedback,updated_at=now()
  returning * into rowout;
  return rowout;
end; $$;
grant execute on function public.refresh_daily_progress(uuid,uuid) to authenticated;

commit;
