-- GK BY PURUSHOTAM SIR — V12.15 PUSH NOTIFICATION SETUP
-- इसे Supabase SQL Editor में केवल एक बार Run करें। यह मौजूदा tables/data को नहीं हटाता।
begin;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_active_idx
on public.push_subscriptions(user_id,is_active);

alter table public.push_subscriptions enable row level security;
revoke all on table public.push_subscriptions from anon, authenticated;

create table if not exists public.student_app_notification_reads (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  notification_id bigint not null references public.app_notifications(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique(student_id,notification_id)
);

alter table public.student_app_notification_reads enable row level security;

drop policy if exists "student_app_notification_reads_own" on public.student_app_notification_reads;
create policy "student_app_notification_reads_own"
on public.student_app_notification_reads
for all to authenticated
using(student_id=auth.uid() or public.is_admin())
with check(student_id=auth.uid() or public.is_admin());

grant select,insert,update,delete on public.student_app_notification_reads to authenticated;
do $$
begin
  if to_regclass('public.student_app_notification_reads_id_seq') is not null then
    execute 'grant usage,select on sequence public.student_app_notification_reads_id_seq to authenticated';
  end if;
end $$;

-- Existing old notifications को नई release पर अचानक unread न दिखाएँ।
insert into public.student_app_notification_reads(student_id,notification_id)
select p.id,n.id
from public.profiles p
cross join public.app_notifications n
where coalesce(n.is_active,true)=true
on conflict(student_id,notification_id) do nothing;

commit;

select
  'V12.15 PUSH NOTIFICATION SETUP SUCCESS' as status,
  (select count(*) from information_schema.tables where table_schema='public' and table_name='push_subscriptions') as push_subscription_table,
  (select count(*) from information_schema.tables where table_schema='public' and table_name='student_app_notification_reads') as notification_reads_table;
