begin;

create table if not exists public.target_verification_questions (
  id bigint generated by default as identity primary key,
  target_id bigint,
  schedule_day_id bigint,
  question_text text not null,
  options jsonb not null default '[]'::jsonb,
  correct_option integer not null,
  explanation text,
  question_hidden boolean not null default true,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_target_verification_target
on public.target_verification_questions(target_id);

create index if not exists idx_target_verification_day
on public.target_verification_questions(schedule_day_id);

alter table public.target_verification_questions enable row level security;

drop policy if exists "verification_read_authenticated"
on public.target_verification_questions;

create policy "verification_read_authenticated"
on public.target_verification_questions
for select
to authenticated
using (true);

drop policy if exists "verification_admin_all"
on public.target_verification_questions;

create policy "verification_admin_all"
on public.target_verification_questions
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role::text = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role::text = 'admin'
  )
);

commit;
