let user=null,profile=null,currentDay=null,currentTargets=[],targetCompletionMap=new Map(),verificationMap=new Map(),materials=[],latestDailyTest=null;
const SUBJECT_CLASS={"Maths":"subject-maths","Mathematics":"subject-maths","Reasoning":"subject-reasoning","Haryana GK":"subject-haryana","Hindi":"subject-hindi","Science":"subject-science","Polity":"subject-polity","History":"subject-history","Geography":"subject-geography","Static GK":"subject-static","Computer":"subject-computer","BNS/BNSS/BSA":"subject-law","BNS":"subject-law","BNSS":"subject-law","BSA":"subject-law"};
function tab(name,el){["home","targets","tests","oneliners","pdfs","notifications","profile"].forEach(x=>document.getElementById(x+"Tab").classList.toggle("hidden",x!==name));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));if(el)el.classList.add("active")}
function sclass(s){return SUBJECT_CLASS[s]||"subject-other"}
async function init(){registerSW();user=await requireAuth();if(!user)return;profile=await getProfile(user.id);await loadDayData();await Promise.all([renderHome(),renderTargets(),loadTests(),loadOneLiners(),loadPdfs(),renderProfile(),loadNotifications()])}
async function loadDayData(){const today=new Date().toISOString().slice(0,10);let r=await sb.from("schedule_days").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).eq("manual_lock",false).or(`manual_unlock.eq.true,and(manual_unlock.eq.false,day_date.lte.${today})`).order("day_number",{ascending:false}).limit(1).maybeSingle();currentDay=r.data;if(!currentDay)return;const tr=await sb.from("daily_targets").select("*").eq("schedule_day_id",currentDay.id).order("target_order");currentTargets=tr.data||[];const tc=await sb.from("target_completions").select("*").eq("user_id",user.id);(tc.data||[]).forEach(x=>targetCompletionMap.set(x.target_id,x));const vr=await sb.from("verification_questions").select("*").eq("schedule_day_id",currentDay.id).eq("is_active",true);(vr.data||[]).forEach(x=>verificationMap.set(x.target_id||x.id,x));const mr=await sb.from("study_materials").select("*").eq("schedule_day_id",currentDay.id).eq("status","published").order("created_at");materials=mr.data||[];const tt=await sb.from("tests").select("*").eq("schedule_day_id",currentDay.id).eq("status","published").order("created_at",{ascending:false}).limit(1);latestDailyTest=tt.data?.[0]||null}
async function latestAttempt(){if(!latestDailyTest)return null;const r=await sb.from("test_attempts").select("*").eq("user_id",user.id).eq("test_id",latestDailyTest.id).eq("status","submitted").order("submitted_at",{ascending:false}).limit(1);return r.data?.[0]||null}
async function statusModel(){const a=await latestAttempt(),total=currentTargets.length,done=currentTargets.filter(t=>targetCompletionMap.has(t.id)).length,all=total>0&&done===total,testDone=!!a,score=a?.percentage||0;let key="notstarted",title="Work Complete नहीं हुआ है ❌",msg="आपने आज का कोई भी Target पूरा नहीं किया है।";if(done>0&&!all){key="pending";title="आज का Target पूरा करें ⚠️";msg=`आपने ${total} में से ${done} Target पूरे किए हैं।`}if(all&&!testDone){key="pending";title="Target पूरा — Test Pending ⚠️";msg="सभी Targets verified हैं। अब Daily Test complete करें।"}if(all&&testDone&&score>=80){key="excellent";title="Excellent 🌹";msg="बहुत बढ़िया! सभी Target और Test शानदार तरीके से पूरा।"}else if(all&&testDone){key="verygood";title="Very Good 👍";msg="आपने सभी Target और Test पूरा किया।"}return{key,title,msg,total,done,testDone,score}}
async function renderHome(){const st=await statusModel();homeBox.innerHTML=`<div class="hello">Hello, ${esc(profile?.full_name||"Student")} 👋</div><div class="muted">Welcome Back!</div><div class="status-hero ${st.key}"><div class="small">आज का संदेश</div><h2>${esc(st.title)}</h2><p>${esc(st.msg)}</p></div><div class="card"><h3>Today's Progress</h3><div class="progress-icons"><div class="progress-box"><div class="circle ${st.done>0?"done":"bad"}">${st.done>0?"✓":"×"}</div><div>Class</div></div><div class="progress-box"><div class="circle ${materials.length?"done":"pending"}">${materials.length?"✓":"–"}</div><div>PDF</div></div><div class="progress-box"><div class="circle ${st.testDone?"done":"pending"}">${st.testDone?"✓":"–"}</div><div>Test</div></div><div class="progress-box"><div class="circle ${st.done===st.total&&st.total?"done":"pending"}">${st.done}/${st.total}</div><div>Total</div></div></div></div><div class="stat-row" style="margin-top:10px"><div class="stat-mini"><div class="muted">Streak</div><div class="kpi">${profile?.current_streak||0} Days</div></div><div class="stat-mini"><div class="muted">Average Test</div><div class="kpi">${profile?.average_test_percentage||0}%</div></div></div>`}
async function renderTargets(){let html=`<div class="row wrap"><h3>Day ${currentDay?.day_number||"-"}</h3><div class="muted">${currentDay?fmtDate(currentDay.day_date):""}</div></div>`;for(const t of currentTargets){const done=targetCompletionMap.has(t.id),v=verificationMap.get(t.id)||null;html+=`<div class="target-card ${sclass(t.subject)}"><div class="small">${esc(t.subject)}</div><div class="topic">${esc(t.topic)}</div><div style="margin-top:8px">${done?'<span class="badge badge-green">Verified & Completed ✓</span>':v?'<span class="badge badge-orange">Verification Pending</span>':'<span class="badge badge-red">Teacher verification not added</span>'}</div></div>`;if(!done&&v)html+=`<div class="verify-card"><h4>${v.verification_kind==="pdf"?"PDF Question":"Class Question"}</h4><p>${esc(v.question_text)}</p><input id="vq_${v.id}" placeholder="अपना उत्तर लिखें"><div style="height:8px"></div><button class="btn btn-green" onclick="verifyTarget('${v.id}','${t.id}')">Submit Answer</button></div>`}if(latestDailyTest)html+=`<div class="card"><div class="row wrap"><div><b>Daily Test</b><div class="muted">${esc(latestDailyTest.title)}</div></div><a class="btn btn-blue" href="test.html?id=${latestDailyTest.id}">Start Test</a></div></div>`;targetsBox.innerHTML=html}
async function verifyTarget(vId,targetId){const a=document.getElementById("vq_"+vId)?.value?.trim();if(!a){toast("उत्तर भरें","error");return}const r=await sb.rpc("submit_target_verification",{p_verification_question_id:vId,p_target_id:targetId,p_answer:a});if(r.error){toast(r.error.message,"error");return}if(r.data===true){toast("सही उत्तर — Target Completed ✓","success");targetCompletionMap.set(targetId,{target_id:targetId});await sb.rpc("refresh_daily_progress",{p_user_id:user.id,p_schedule_day_id:currentDay.id});await renderTargets();await renderHome()}else toast("उत्तर सही नहीं है।","error")}
async function loadTests(){const r=await sb.from("tests").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).eq("status","published").order("created_at",{ascending:false});testsList.innerHTML=(r.data||[]).map(t=>`<div class="item"><div class="row wrap"><div><b>${esc(t.title)}</b><div class="muted">${t.total_questions} Questions • ${t.time_limit_minutes||"-"} min</div></div><a class="btn btn-blue" href="test.html?id=${t.id}">Start Test</a></div></div>`).join("")||'<div class="card">अभी कोई Test नहीं है।</div>'}
async function loadOneLiners(){const r=await sb.from("one_liners").select("*").eq("status","published").order("created_at",{ascending:false});oneLinersList.innerHTML=(r.data||[]).map((x,i)=>`<div class="item"><div class="small muted">${esc(x.subject||"One-Liner")}</div><b>${i+1}. ${esc(x.question)}</b><p style="margin-bottom:0"><span class="badge badge-green">उत्तर</span> ${esc(x.answer)}</p></div>`).join("")||'<div class="card">अभी कोई One-Liner उपलब्ध नहीं है।</div>'}
async function loadPdfs(){const r=await sb.from("study_materials").select("*,schedule_days(day_number)").eq("status","published").order("created_at",{ascending:false});pdfList.innerHTML=(r.data||[]).map(m=>`<div class="item row wrap"><div><b>${esc(m.title)}</b><div class="muted">Day ${m.schedule_days?.day_number||"-"}</div></div><button class="btn btn-blue" onclick="openPdf('${m.storage_path}')">Open PDF</button></div>`).join("")||'<div class="card">अभी कोई PDF नहीं है।</div>'}
async function openPdf(path){const r=await sb.storage.from("study-pdfs").createSignedUrl(path,600);if(r.error){toast(r.error.message,"error");return}window.open(r.data.signedUrl,"_blank")}
async function renderProfile(){profileBox.innerHTML=`<div class="card"><h3>${esc(profile?.full_name||"Student")}</h3><p>Mobile: ${esc(profile?.phone||"")}</p><p>Completed Days: ${profile?.total_completed_days||0}</p><p>Average Test: ${profile?.average_test_percentage||0}%</p><p>Current Streak: ${profile?.current_streak||0}</p><button class="btn btn-red" onclick="logout()">Logout</button></div>`}
init();


let notificationRows=[];
async function loadNotifications(){
 const br=await sb.from("broadcast_messages").select("*").eq("is_active",true).order("created_at",{ascending:false}).limit(50);
 const ar=await sb.from("app_notifications").select("*").eq("is_active",true).order("created_at",{ascending:false}).limit(50);
 const reads=await sb.from("student_notification_reads").select("broadcast_id").eq("student_id",user.id);
 const readSet=new Set((reads.data||[]).map(x=>String(x.broadcast_id)));
 const broadcasts=(br.data||[]).map(x=>({id:'b_'+x.id,rawId:x.id,title:x.title,message:x.message,type:x.message_type||'info',created_at:x.created_at,unread:!readSet.has(String(x.id)),isBroadcast:true}));
 const auto=(ar.data||[]).filter(x=>x.related_type!=='broadcast').map(x=>({id:'a_'+x.id,title:x.title,message:x.message,type:x.notification_type||'info',created_at:x.created_at,unread:false,isBroadcast:false}));
 notificationRows=[...broadcasts,...auto].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
 const unread=notificationRows.filter(x=>x.unread).length,b=document.getElementById('notificationBadge');if(b){b.textContent=unread;b.classList.toggle('hidden',!unread)}
 renderNotifications();
}
function renderNotifications(){const el=document.getElementById('notificationsList');if(!el)return;el.innerHTML=notificationRows.map(x=>`<div class="item notice-premium ${esc(x.type)} ${x.unread?'notice-unread':''}"><div class="row wrap"><b>${esc(x.title)}</b>${x.unread?'<span class="badge badge-red">NEW</span>':''}</div><p>${esc(x.message)}</p><div class="small muted">${new Date(x.created_at).toLocaleString('en-IN')}</div></div>`).join('')||'<div class="card">अभी कोई Notification नहीं है।</div>'}
function openNotifications(){tab('notifications');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'));markAllNotificationsRead()}
async function markAllNotificationsRead(){const unread=notificationRows.filter(x=>x.unread&&x.isBroadcast);for(const x of unread){await sb.from('student_notification_reads').upsert({student_id:user.id,broadcast_id:x.rawId},{onConflict:'student_id,broadcast_id'})}await loadNotifications()}
