let user=null,profile=null,currentDay=null,currentTargets=[],targetCompletionMap=new Map(),verificationRows=[],materials=[],tests=[];
const SUBJECT_CLASS={"Maths":"subject-maths","Mathematics":"subject-maths","Reasoning":"subject-reasoning","Haryana GK":"subject-haryana","Hindi":"subject-hindi","Science":"subject-science","Polity":"subject-polity","History":"subject-history","Geography":"subject-geography","Static GK":"subject-static","Computer":"subject-computer","BNS/BNSS/BSA":"subject-law"};
function tab(name,el){["home","targets","tests","oneliners","pdfs","notifications","profile"].forEach(x=>document.getElementById(x+"Tab").classList.toggle("hidden",x!==name));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));if(el)el.classList.add("active")}
function sclass(s){return SUBJECT_CLASS[s]||"subject-other"}
async function init(){registerSW();user=await requireAuth();if(!user)return;profile=await getProfile(user.id);await loadCurrentDay();await Promise.all([renderHome(),renderTargets(),loadTests(),loadOneLiners(),loadPdfs(),loadNotifications(),renderProfile()])}
async function loadCurrentDay(){const today=new Date().toISOString().slice(0,10);let r=await sb.from("schedule_days").select("*").eq("batch_id",APP_CONFIG.BATCH_ID).eq("manual_lock",false).or(`manual_unlock.eq.true,and(manual_unlock.eq.false,day_date.lte.${today})`).order("day_number",{ascending:false}).limit(1).maybeSingle();currentDay=r.data;if(!currentDay)return;const [tr,tc,vr,mr,te]=await Promise.all([sb.from("daily_targets").select("*").eq("schedule_day_id",currentDay.id).eq("status","published").order("target_order"),sb.from("target_completions").select("*").eq("user_id",user.id),sb.from("verification_questions").select("*").eq("schedule_day_id",currentDay.id).eq("is_active",true).order("created_at"),sb.from("study_materials").select("*").eq("schedule_day_id",currentDay.id).eq("status","published").order("created_at"),sb.from("tests").select("*").eq("schedule_day_id",currentDay.id).eq("status","published").order("created_at")]);currentTargets=tr.data||[];(tc.data||[]).forEach(x=>targetCompletionMap.set(x.target_id,x));verificationRows=vr.data||[];materials=mr.data||[];tests=te.data||[]}
function finalTest(){return tests.filter(t=>t.is_final_daily).slice(-1)[0]||null}
async function bestAttempt(testId){if(!testId)return null;const r=await sb.from("test_attempts").select("*").eq("user_id",user.id).eq("test_id",testId).eq("status","submitted").order("percentage",{ascending:false}).limit(1);return r.data?.[0]||null}
async function renderHome(){if(!currentDay){homeBox.innerHTML='<div class="card">आज का Target उपलब्ध नहीं है।</div>';return}const ft=finalTest(),fa=await bestAttempt(ft?.id),done=currentTargets.filter(t=>targetCompletionMap.has(t.id)).length,total=currentTargets.length,passed=!ft||(fa&&fa.percentage>=ft.passing_percent);const status=done===0?'Work Complete नहीं हुआ है ❌':done<total?'आज का Target पूरा करें ⚠️':!passed?'Final Test Pass करना बाकी है 📝':'आज का Target Complete 🎉';homeBox.innerHTML=`<div class="hello">Hello, ${esc(profile?.full_name||'Student')} 👋</div><div class="muted">Day ${currentDay.day_number} • ${fmtDate(currentDay.day_date)}</div><div class="status-hero hero-premium"><div class="small">आज का संदेश</div><h2>${status}</h2><p>Class → Verification → PDF → Final Mock Test → Target Complete</p></div><div class="workflow-steps"><div class="workflow-step ${done?'done':''}"><div class="workflow-icon">▶️</div><div class="workflow-title">Class</div></div><div class="workflow-step ${done?'done':''}"><div class="workflow-icon">✅</div><div class="workflow-title">Verification</div></div><div class="workflow-step ${materials.length?'done':''}"><div class="workflow-icon">📄</div><div class="workflow-title">PDF</div></div><div class="workflow-step ${passed&&done===total?'done':''}"><div class="workflow-icon">📝</div><div class="workflow-title">Final Test</div></div></div><div class="stat-row" style="margin-top:12px"><div class="stat-mini"><div class="muted">Targets</div><div class="kpi">${done}/${total}</div></div><div class="stat-mini"><div class="muted">Streak</div><div class="kpi">${profile?.current_streak||0}</div></div></div>`}
function targetVerifications(targetId){return verificationRows.filter(v=>String(v.target_id)===String(targetId))}
async function renderTargets(){if(!currentDay){targetsBox.innerHTML='<div class="card">No target.</div>';return}let html=`<div class="row wrap"><div><h3>Day ${currentDay.day_number}</h3><div class="muted">${fmtDate(currentDay.day_date)}</div></div></div>`;for(const t of currentTargets){const done=targetCompletionMap.has(t.id),vs=targetVerifications(t.id);html+=`<div class="target-card ${sclass(t.subject)}"><div class="small">${esc(t.subject)}</div><div class="topic">${esc(t.topic)}</div>${t.youtube_url?`<p><a class="btn btn-red" target="_blank" href="${esc(t.youtube_url)}">▶ Watch YouTube Class</a></p>`:'<p class="small">Class link अभी add नहीं किया गया।</p>'}<div>${done?'<span class="badge badge-green">Verified & Completed ✓</span>':'<span class="badge badge-orange">Verification Pending</span>'}</div></div>`;if(!done&&vs.length){for(const v of vs){const opts=Array.isArray(v.options)?v.options:[];html+=`<div class="verify-card"><h4>Class Verification</h4>${v.show_question?`<p><b>${esc(v.question_text)}</b></p>`:'<p class="muted"><b>Question class में पूछा गया था। सही option चुनिए।</b></p>'}<div class="choice-grid" id="choices_${v.id}">${opts.map((o,i)=>`<button class="choice-option" onclick="selectVerifyOption('${v.id}',${i},this)">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><input type="hidden" id="vq_${v.id}"><div style="height:8px"></div><button class="btn btn-green" onclick="verifyTarget('${v.id}','${t.id}')">Submit Answer</button><div id="vres_${v.id}" class="small" style="margin-top:8px"></div></div>`}}}const ft=finalTest();if(ft)html+=`<div class="card final-test-card"><div class="row wrap"><div><b>Daily Final Mock Test</b><div class="muted">Pass: ${ft.passing_percent}% • ${ft.total_questions} Questions</div></div><a class="btn btn-purple btn-blue" href="test.html?id=${ft.id}">Start Final Test</a></div></div>`;targetsBox.innerHTML=html}
function selectVerifyOption(id,i,el){document.querySelectorAll(`#choices_${id} .choice-option`).forEach(x=>x.classList.remove('selected'));el.classList.add('selected');document.getElementById('vq_'+id).value=String(i)}
async function verifyTarget(vId,targetId){
  const answer=document.getElementById('vq_'+vId)?.value;
  if(answer===''||answer===undefined){toast('पहले कोई एक option चुनिए।','error');return}
  const r=await sb.rpc('submit_target_verification',{p_verification_question_id:vId,p_target_id:targetId,p_answer:answer});
  const box=document.getElementById('vres_'+vId);
  if(r.error){toast(r.error.message,'error');return}
  if(r.data===true){
    const v=verificationRows.find(x=>String(x.id)===String(vId));
    box.innerHTML='<span class="badge badge-green">✅ Correct Answer</span>'+(v?.explanation?`<div class="verification-explanation"><b>व्याख्या:</b> ${esc(v.explanation)}</div>`:'');
    const card=box.closest('.verify-card'); if(card){card.querySelectorAll('button.choice-option').forEach(b=>b.disabled=true);const sbt=card.querySelector('button.btn-green');if(sbt)sbt.disabled=true}
    const done=await sb.from('target_completions').select('target_id').eq('user_id',user.id).eq('target_id',targetId).maybeSingle();
    if(done.data){
      targetCompletionMap.set(targetId,{target_id:targetId});
      await sb.rpc('refresh_daily_progress',{p_user_id:user.id,p_schedule_day_id:currentDay.id});
      box.innerHTML+='<div style="margin-top:8px"><span class="badge badge-green">🎉 सभी Verification सही — Target Verified</span></div>';
      setTimeout(async()=>{await renderTargets();await renderHome()},850)
    }else{
      box.innerHTML+='<div class="small muted" style="margin-top:8px">इस Target के बाकी verification question भी सही करें।</div>'
    }
  }else{
    box.innerHTML='<span class="badge badge-red">❌ Answer Wrong — Try Again</span>'
  }
}
async function loadTests(){const r=await sb.from('tests').select('*').eq('batch_id',APP_CONFIG.BATCH_ID).eq('status','published').order('created_at',{ascending:false});testsList.innerHTML=(r.data||[]).map(t=>`<div class="item"><div class="row wrap"><div><b>${esc(t.title)}</b><div class="muted">${t.total_questions} Questions • Pass ${t.passing_percent||0}%${t.is_final_daily?' • Final Daily Test':''}</div></div><a class="btn btn-blue" href="test.html?id=${t.id}">Start Test</a></div></div>`).join('')||'<div class="card">अभी कोई Test नहीं है।</div>'}
let oneLinerRows=[];async function loadOneLiners(){const r=await sb.from('one_liners').select('*').eq('status','published').order('subject').order('topic').order('created_at');oneLinerRows=r.data||[];const subjects=[...new Set(oneLinerRows.map(x=>x.subject||'General'))];oneLinerFilters.innerHTML=`<label>Subject</label><select id="olSubject" onchange="renderOneLiners()"><option value="">All Subjects</option>${subjects.map(s=>`<option>${esc(s)}</option>`).join('')}</select><label style="margin-top:8px">Topic</label><select id="olTopic" onchange="renderOneLiners()"><option value="">All Topics</option></select>`;document.getElementById('olSubject').addEventListener('change',updateTopicFilter);updateTopicFilter();renderOneLiners()}
function updateTopicFilter(){const s=document.getElementById('olSubject')?.value||'';const topics=[...new Set(oneLinerRows.filter(x=>!s||(x.subject||'General')===s).map(x=>x.topic||'General'))];document.getElementById('olTopic').innerHTML='<option value="">All Topics</option>'+topics.map(t=>`<option>${esc(t)}</option>`).join('');renderOneLiners()}
function renderOneLiners(){const s=document.getElementById('olSubject')?.value||'',t=document.getElementById('olTopic')?.value||'';const rows=oneLinerRows.filter(x=>(!s||(x.subject||'General')===s)&&(!t||(x.topic||'General')===t));const groups={};rows.forEach(x=>{const k=x.topic||'General';(groups[k]??=[]).push(x)});oneLinersList.innerHTML=Object.entries(groups).map(([topic,items])=>`<div class="topic-group"><div class="topic-group-title">${esc(topic)}</div>${items.map((x,i)=>`<div class="item"><span class="topic-chip">${esc(x.subject||'General')}</span><p><b>${i+1}. ${esc(x.question)}</b></p><p><span class="badge badge-green">उत्तर</span> ${esc(x.answer)}</p></div>`).join('')}</div>`).join('')||'<div class="card">कोई One-Liner नहीं मिला।</div>'}
async function loadPdfs(){
  const r=await sb.from('study_materials').select('*,schedule_days(day_number,day_date,manual_lock,manual_unlock)').eq('status','published').order('created_at',{ascending:false});
  const today=new Date().toISOString().slice(0,10);
  const rows=(r.data||[]).filter(m=>{
    const d=m.schedule_days;if(!d)return true;
    if(d.manual_lock)return false;
    return d.manual_unlock||d.day_date<=today;
  });
  pdfList.innerHTML=rows.map(m=>`<div class="item pdf-read-card"><div class="row wrap"><div><b>${esc(m.title)}</b><div class="muted">Day ${m.schedule_days?.day_number||'-'} • ${m.access_mode==='direct_download'?'Direct Download':m.access_mode==='test_required'?`Test Gate ${m.download_pass_percent}%`:'Read Only'}</div></div><div class="row wrap"><button class="btn btn-blue" onclick="readPdf('${m.id}','${m.storage_path}','${esc(m.title)}')">Read PDF</button>${m.access_mode!=='read_only'?`<button class="btn btn-green" onclick="downloadPdf('${m.id}','${m.storage_path}')">Download</button>`:''}</div></div></div>`).join('')||'<div class="card">अभी कोई PDF नहीं है।</div>'
}
async function readPdf(id,path,title){
  const gate=await sb.rpc('can_read_material',{p_material_id:id});
  if(gate.error){toast(gate.error.message,'error');return}
  if(!gate.data){toast('पहले Class Verification पूरा करें, तभी PDF खुलेगी।','error');return}
  const rr=await sb.storage.from('study-pdfs').createSignedUrl(path,600);
  if(rr.error){toast(rr.error.message,'error');return}
  const modal=document.createElement('div');modal.className='pdf-modal';modal.innerHTML=`<div class="pdf-modal-box"><div class="pdf-modal-head"><b>${title}</b><button class="btn btn-red" onclick="this.closest('.pdf-modal').remove()">Close</button></div><iframe src="${rr.data.signedUrl}#toolbar=0&navpanes=0"></iframe></div>`;document.body.appendChild(modal)
}
async function downloadPdf(id,path){const ok=await sb.rpc('can_download_material',{p_material_id:id});if(ok.error){toast(ok.error.message,'error');return}if(!ok.data){toast('PDF Download Locked — Required Test passing score पूरा करें।','error');return}const rr=await sb.storage.from('study-pdfs').createSignedUrl(path,120);if(rr.error){toast(rr.error.message,'error');return}const a=document.createElement('a');a.href=rr.data.signedUrl;a.download='study-material.pdf';a.target='_blank';a.click()}
async function renderProfile(){profileBox.innerHTML=`<div class="card"><h3>${esc(profile?.full_name||'Student')}</h3><p>Mobile: ${esc(profile?.phone||'')}</p><p>Completed Days: ${profile?.total_completed_days||0}</p><p>Average Test: ${profile?.average_test_percentage||0}%</p><p>Current Streak: ${profile?.current_streak||0}</p><button class="btn btn-red" onclick="logout()">Logout</button></div>`}
let notificationRows=[];async function loadNotifications(){const [br,ar,reads]=await Promise.all([sb.from('broadcast_messages').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(50),sb.from('app_notifications').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(50),sb.from('student_notification_reads').select('broadcast_id').eq('student_id',user.id)]);const readSet=new Set((reads.data||[]).map(x=>String(x.broadcast_id)));const broadcasts=(br.data||[]).map(x=>({id:'b_'+x.id,rawId:x.id,title:x.title,message:x.message,type:x.message_type||'info',created_at:x.created_at,unread:!readSet.has(String(x.id)),isBroadcast:true}));const auto=(ar.data||[]).filter(x=>x.related_type!=='broadcast').map(x=>({id:'a_'+x.id,title:x.title,message:x.message,type:x.notification_type||'info',created_at:x.created_at,unread:false,isBroadcast:false}));notificationRows=[...broadcasts,...auto].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const unread=notificationRows.filter(x=>x.unread).length,b=document.getElementById('notificationBadge');if(b){b.textContent=unread;b.classList.toggle('hidden',!unread)}renderNotifications()}
function renderNotifications(){notificationsList.innerHTML=notificationRows.map(x=>`<div class="item notice-premium ${esc(x.type)}"><div class="row"><b>${esc(x.title)}</b>${x.unread?'<span class="badge badge-red">NEW</span>':''}</div><p>${esc(x.message)}</p><div class="small muted">${new Date(x.created_at).toLocaleString('en-IN')}</div></div>`).join('')||'<div class="card">अभी कोई Notification नहीं है।</div>'}
function openNotifications(){tab('notifications');markAllNotificationsRead()}
async function markAllNotificationsRead(){for(const x of notificationRows.filter(x=>x.unread&&x.isBroadcast)){await sb.from('student_notification_reads').upsert({student_id:user.id,broadcast_id:x.rawId},{onConflict:'student_id,broadcast_id'})}await loadNotifications()}
init();
